name: connect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython
  - sqlalchemy
  # Depending on your exact setup a different mysql connector may work better than another
  - pymysql
  - mysqlclient
  - mysql-connector-python